---

- name: TOWER | loadbalancer | Stop if we dont have the required variables
  fail:
    msg: Computer says no. This role needs 'router_id', 'vrrp_state' and 'vip_addresses' vars to be set.
  when: >
      ( router_id is undefined )
      or ( vrrp_state is undefined )
      or ( vip_addresses is undefined )
  tags:
  - loadbalancer

- name: TOWER | loadbalancer | Install haproxy and keepalived
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - haproxy
    - keepalived
  tags:
  - loadbalancer

- name: TOWER | loadbalancer | Push out haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0600
  notify: restart haproxy
  tags:
  - loadbalancer

- name: TOWER | loadbalancer | Push out tower SSL pem file
  copy:
    src: tower.pem
    dest: /etc/ssl/certs/tower.pem
  notify: restart haproxy
  tags:
  - loadbalancer

- name: TOWER | loadbalancer | Start and enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
  tags:
  - loadbalancer

- name: TOWER | loadbalancer | copy over our keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived
  tags:
  - loadbalancer

- name: TOWER | loadbalancer | start and enable keepalived
  service:
    name: keepalived
    state: started
    enabled: yes
  tags:
  - loadbalancer
